### ISSUE TITLE
Critical: breaks require.js

### ISSUE THREAD

**Issue by jescalan** [segmentio/analytics.js#515]
This just happened recently and brought down all javascript on a production website for us. We are using require.js on the website in question, and analytics.js must have updated behind the scenes with some type of change that causes require.js to break.

The only way to fix this problem for us is to remove analytics.js from the site and replace it with a stub in the meantime.

The error being emitted, specifically, [is this one](http://requirejs.org/docs/errors.html#mismatch). This should be able to be reproduced by including the analytics.js snippet on any page that is using require.js in any way. As part of the debugging process, I slimmed down the require config to just load one simple file that `console.log`s, and also removed all other scripts. It was only removing analytics.js that would fix the problem though, so I'm fairly confident this is some sort of issue with the way the script is compiled out. If a variable called `define` is written in the global scope this is likely the cause.

What's even more unnerving is that the website was actually using an older version of the analytics.js snippet -- version `2.0.9` -- but it appears as if this version was also updated directly through the CDN it loads from and caused the site to break suddenly without us changing anything.

**Comment by sperand-io** [comment]
Thanks for flagging this.  We've rolled back globally and will not be moving forward with the release until we've found, tested, and fixed the root cause of this issue. I'll follow up in this thread with more information as soon as possible.

**Comment by hansent** [comment]
We are experiencing similar issues

**Comment by f2prateek** [comment]
@hansent Can you let us know the URL of your site?

**Comment by jgershen** [comment]
@hansent: Also, are you currently experiencing this issue?

**Comment by hansent** [comment]
yes, still experiencing the issue.  it seems like it only causes erros if we enable more than one integration.

we have disabled all integrations except intercom atm for https://proofme.com  since otherwise our site and app become completly broken.  testing with our proofme-local segment source (but this site is not accessible from outside) atm and still experiencing issues if more than one integration is enabled (still verifying this is the exact cause, it takes a little until the settings on segment propagate, but I am checking analytics.Integrations  to verify)

**Comment by jgershen** [comment]
@hansent Got it, thanks for reporting. Can you share any additional information or traces? 
We're trying to understand whether this is exactly the same issue or is related to the enabled integrations.

**Comment by hansent** [comment]
actually, seems to be tied to amplitude integration being enabled?

**Comment by jgershen** [comment]
We've been testing with requirejs, amplitude, and intercom enabled, and aren't able to reproduce any errors. I suspect there's something missing in our testing environment which is present in yours. Any more information you can share from your dev site?

**Comment by hansent** [comment]
sometimes a define call like gets passed the amplitude integration instead for the module that was specified.  e.g.
```
define(['underscore', 'jquery', 'exports'], function(_, $, exports) {
 // _ here is Amplitude
}
```
<img width="569" alt="screen 23" src="https://cloud.githubusercontent.com/assets/137617/16603171/b18a503c-42df-11e6-9630-b9a55b17ba5a.png">

**Comment by f2prateek** [comment]
@hansent For our reference, can you share the exact error you're seeing in the console? Could you also shoot us an email with a screenshot of that error to friends@segment.com?

**Comment by hansent** [comment]
well, it's different every time.  some of them sem to repeat, but have not been able to identify a clear pattern.  i'm guessing it depends on script load order

**Comment by jgershen** [comment]
We'd love any info you have! Still trying to understand what is actually causing this issue.

**Comment by hansent** [comment]
I will setup a seperate segment config for our staging env and give you a link when it's ready

**Comment by jgershen** [comment]
Terrific, thanks! If you'd like to keep the link private, you can also email it to friends@segment.com and just post here that you've sent it, instead of posting it here.

**Comment by ladanazita** [comment]
Feel free to address that to me @hansent , I've been keeping track of this issue. Thanks!

**Comment by jgershen** [comment]
We've tentatively reproduced the issue and are digging into it more. Any additional info you have is still welcome!

**Comment by hansent** [comment]
pretty sure the problem is with the amplitude integration (https://d24n15hnbwhuhn.cloudfront.net/libs/amplitude-2.12.1-min.gz.js)

when it is loaded, it makes a call to define creating an anonymous module and injects itself into requirejs' loading queue (globalDefQueue in requirejs source), without requirejs expecting it.  the module loaded next by requirejs will get the amplitude factory instead of its own (in our debugging usually the next item on the queue)

**Comment by hansent** [comment]
bugsnag also does the same: 
```
    a.Bugsnag = x,
    "function" == typeof define && define.amd ? define([], function() {
        return x
    }) : "object" == typeof module && "object" == typeof module.exports && (module.exports = x)
}(window, window.Bugsnag);
```

basically comes down to this I think: http://requirejs.org/docs/errors.html#mismatch
problem being that the files don't get loaded as a dependency but just get inserted as script tags

**Comment by zowers** [comment]
I'd say analytics.js must not use global `require` and `define` at all

**Comment by ndhoule** [comment]
Hey @hansent—I was able to repro your issue and just pushed a fix to production. I've done some testing in my repro case and wasn't able to reproduce the issue anymore; can you test to confirm that the issue is fixed for you?

**Comment by ndhoule** [comment]
@hansent (and anyone else following this issue):

Pending confirmation that the issue is fixed for you, thought you all would be interested in hearing a summary of exactly what the issue was. Some background first:

As @zowers suggests, we do mask analytics.js from using global `require` and `define` (basically, we wrap analytics.js in an IIFE that sets `require` and `define` to undefined) to ensure that any module that comes with a UMD wrapper doesn't interfere with an AMD loader that's already on the page. There are plenty of modules floating around npm (JSON3 and Lodash are pretty notable ones) so we do this to ensure that a seemingly innocuous dependency update doesn't mess with your AMD loader.

The wrapper we were using before looked roughly like this:

```
(function() {
  var oldDefine;
  if (typeof define === 'function' && define.amd) {
    oldDefine = define;
  }

  // ...
  // Run synchronous analytics.js code
  // ...

  define = oldDefine;
}());
```

This code is more defensive that what I replaced it with to fix this issue (specifically, it handles the case where something in the Analytics.js bundle tests for `window.define`), which looks more like this:

```
(function(define) {
  if (typeof define === 'function' && define.amd) {
    // Just mask 
    define = undefined;
  }

  // ...
  // Run synchronous analytics.js code
  // ...

  define = oldDefine;
}(window.define));
```

The problem with the first wrapper is this: Out of necessity, some integrations—specifically, Bugsnag and Amplitude ([docs](https://github.com/amplitude/Amplitude-Javascript#loading-with-requirejs))—need to load through an AMD loader if it's present on the page; that's because these partners build their libraries as UMD modules, so we must account for that case in the integration. (For an example of this in play: see our [special handling for Amplitude](https://github.com/segment-integrations/analytics.js-integration-amplitude/blob/master/lib/index.js#L67-L83).) The first wrapper in this example interferes with the code as written subtly; it tries to use `window.require` while `window.define` is stubbed out; it's been a while since I've used require.js, but it seems as though that was causing the weird behavior you were seeing. Switching to the second wrapper fixed the issue in my testing.

Going forward, we'll be using the second wrapper, which is a little less robust but acceptably prevents the problems listed above. Secondarily, I'll also be beefing up require.js testing throughout our integrations and build process to make sure we catch future issues like this before they go into production.

Thanks again for the report! Let me know if I can clarify anything within this explanation and let me know if the issue persists—happy to dig deeper into this if you're still experiencing issues.

**Comment by ndhoule** [comment]
@jescalan, @hansent — this seems to be resolved so I'm going to close this issue, but feel free to re-open (or open a new issue) if you encounter any further issues.

**Comment by hansent** [comment]
Thanks!  that fixed it for us. :)

**Comment by jhendley25** [comment]
Just re-implemented segment after experiencing this issue last month (on our production site) and this is issue is still happening for us. Looks like I have to remove our segment integrations again. Luckily I caught it in our staging env before pushing to production. Any idea on when this will be fixed?

**Comment by jgershen** [comment]
@jhendley25 can you provide more details about what you are seeing, and your environment? We have been pretty confident this issue is fixed in production.

**Comment by jhendley25** [comment]
Sure: I'm getting the "Mismatched anonymous define() module: function (){return require("1")}" error. Browser environment - Backbone, Requirejs. We have amplitude turned on as an integration. 

It's an intermittent issue, and doesn't happen every time, but I can't put my finger on any specific time it does happen. Any other info I can provide?

**Comment by ndhoule** [comment]
@jhendley25 Can you send over a URL where we can reproduce? Are you building analytics.js yourself, or are you using the Segment snippet?

If you'd rather send it in private, feel free to ping me at nathan@segment.com.

**Comment by jhendley25** [comment]
Ok, I just sent you an email

**Comment by zowers** [comment]
same `Mismatched anonymous define() module: function (){return require("1")}` here

**Comment by jgershen** [comment]
@zowers Can you email friends@segment.com with a URL where we can reproduce, or more information about the particular situation you're seeing? 

We believe the original issue here is fixed and seeing the `anonymous define()` errors that `require.js` generates are probably indicative of something different or specific to individual users' environments. I'm locking this thread for that reason; following up in individual fora seems more appropriate.
